services:
  # frontend:
  #   container_name: frontend-container
  #   image: frontend
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - front
  #     - back
  # getmetricsapi-container:
  #   container_name: getmetricsapi-container
  #   image: getmetricsapi
  #   ports:
  #     - "8000:8000"
  #   links:
  #     - postgres
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  server-app:
    container_name: server-container
    image: server
    ports:
      - "1234:1234"
    links:
      - postgres
      # - check-location-api
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  # check-location-api:
  #   container_name: check-location-api-container
  #   image: check_location
  #   ports:
  #     - "3005:3005"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000"
    links:
      - postgres
    volumes:
      - ./internal/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./internal/grafana:/etc/grafana/provisioning/dashboards
      - ./internal/grafana/data:/var/lib/grafana/
  postgres:
    container_name: pg-container
    image: postgres
    restart: always
    env_file: 
      - "internal/postgresql/environment/.tsenv"
    ports:
      - "5432:5432"
    volumes:
      - ./internal/postgresql/schema:/docker-entrypoint-initdb.d/
      - ./internal/postgresql/data:/var/lib/postgresql/data/