{
 "title": "CPU Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cpu Day ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  system_cpu AS \"system_cpu\"\nFROM cpu\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  idle_cpu\nFROM cpu\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  total_cpu/100 AS \"total_cpu\"\nFROM cpu\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  user_cpu AS \"user_cpu\"\nFROM cpu\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  total_cpu/100\nFROM cpu\nWHERE\n  $__timeFilter(dia)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  user_cpu\nFROM cpu\nWHERE\n  $__timeFilter(dia)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  system_cpu\nFROM cpu\nWHERE\n  $__timeFilter(dia)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  dia AS \"time\",\n  ip AS metric,\n  idle_cpu\nFROM cpu\nWHERE\n  $__timeFilter(dia)\nORDER BY 1,2"
    }
   ]
  }
 ]
}