---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-location-deployment
spec:
    replicas: 1
    template:
      metadata:
        name: check-location
        labels:
          app: check-location
      spec:
        containers:
          - name: check-location-container
            image: check_location:latest
            imagePullPolicy: Never
            ports:
              - containerPort: 3005
            resources:
                requests:
                  cpu:  10m
                  memory: 10Mi
    selector:
        matchLabels:
          app: check-location
---
apiVersion: v1
kind: Service
metadata:
  name: check-location-svc
spec:
  type: NodePort
  ports:
    - port: 3005
      nodePort: 30001
  selector:
    app: check-location
---