---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api-deployment
spec:
    replicas: 1
    template:
      metadata:
        name: metrics-api
        labels:
          app: metrics-api
      spec:
        containers:
          - name: metrics-api-container
            image: getmetricsapi:latest
            imagePullPolicy: Never
            ports:
              - containerPort: 8000
            resources:
                requests:
                  cpu:  10m
                  memory: 10Mi
    selector:
        matchLabels:
          app: metrics-api
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-api-svc
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30002
  selector:
    app: metrics-api
---